### ISSUE TITLE
Exception: OneDrive storage not yet configured

### ISSUE THREAD

**Issue by thalesmaoa** [hevelius/files_external_onedrive#15]
I was so happy with the OneDrive capability, but I'm getting this error some time latter.

I've configured as stated in README file. I've got the green check and can sync normally. No problem so far. After few hours I get and error:

```
HTTP transmission error
```

![image](https://user-images.githubusercontent.com/14074573/65352154-4affe980-dbc0-11e9-9d80-87e4cb489db1.png)

When I check my web for the configuration:

![image](https://user-images.githubusercontent.com/14074573/65352185-5fdc7d00-dbc0-11e9-8e1e-99690144fe48.png)

Red mark. 

If I erase my client secret in Azure and create a new one, it starts working again for few hours.
EDIT: I can even use the same secret, but I need to erase to validate again!

I'm lost!

**Comment by thalesmaoa** [comment]
After some tests I've found that adding OneDrive from admin panel I get this error, however from user panel it is ok.

**Comment by hevelius** [comment]
Hi @thalesmaoa, 
glad to ear this. Other useful informations about first connection and tips to create azure app could be found on https://github.com/hevelius/files_external_onedrive/issues/3
