### ISSUE TITLE
Onedrive successfully set up, but makes the server stall

### ISSUE THREAD

**Issue by Cwellan** [hevelius/files_external_onedrive#24]
Once everything is set up properly, NC server stalls and there is almost no way to have a page without waiting more than 60s (then, timeout occurs). 
The only way to stop it is to re-run the apache server and php service, and disable onedrive storage without triggering a webdav scan of OneDrive. 
Is it related to the volume of data of the Onedrive set up ? (~ 1TB of Data)
Using Nextcloud 16 on BSD, Onedrive personal with approx 1TB of Data

**Comment by hevelius** [comment]
Hi @Cwellan,
it's not related to the volume of data. It's an issue resolved in the latest release v1.0.7 just deployed.
Try first to remove the external storage then update to the latest and added again the e.s.

**Comment by Cwellan** [comment]
Okay I'll do that.
Congratulations on solving this issue quickly !

I am interested in knowing the root causes. May you explain ?
