### ISSUE TITLE
Creating Onedrive App

### ISSUE THREAD

**Issue by arv4** [hevelius/files_external_onedrive#3]
I tried to create a onedrive app, but I encountered several problems.

Azure does not accept the Authentication Redirect URI
`http://path/to/nextcloud/index.php/settings/admin?sectionid=storage`.
I am getting the error message:
`Does not contain query strings`
Also the URL must start with HTTPS.
Maybe the Redirect URI should be
`https://path/to/nextcloud/index.php/settings/admin/externalstorages`?

After clicking "Grant access" in my Nextcloud installation nothing happens.
An XHR request gets send to `http://path/to/nextcloud/index.php/apps/files_external/ajax/oauth2.php`, but I don't get redirected or get any error message.

I am using Nextcloud 16.0.1

**Comment by hevelius** [comment]
The correct paths are
https://path/to/nextcloud/index.php/settings/user/externalstorages
https://path/to/nextcloud/index.php/settings/admin/externalstorages

without querystring.

Sorry the instructions to configuring Azure is a little confused. I hope to work on as soon as possible.

For the XHR request is there any error on your browser console?

**Comment by Maverick1983** [comment]
Not working when click "Grand access". I will redirect to microsoft login and immediatly I receve error on attach file.
![Error](https://user-images.githubusercontent.com/20558694/61528749-dc67a980-aa1f-11e9-8f65-fcb0c65cfcf6.png)

**Comment by hevelius** [comment]
> Not working when click "Grand access". I will redirect to microsoft login and immediatly I receve error on attach file.
> ![Error](https://user-images.githubusercontent.com/20558694/61528749-dc67a980-aa1f-11e9-8f65-fcb0c65cfcf6.png)
> 
> I have Client Id configured
> 
> ![Error2](https://user-images.githubusercontent.com/20558694/61528814-0751fd80-aa20-11e9-81c3-6c578320c2fe.png)

seems to be a mistake on azure... Have you give right permissions?

**Comment by Maverick1983** [comment]
It's my Azure

**Comment by arv4** [comment]
Found an error maybe realated to my problem.
My Nextcloud tries to load a script from a nonexistent location. It is installed into "subdirectory", but tries to load a script from "subdirectory//subdirectory"

```Loading failed for the <script> with source “https://example.com/subdirectory//subdirectory/apps/files_external_onedrive/js/onedrive.js?v=241bed0d-0”.```

**Comment by Maverick1983** [comment]
@arv4 You can see here [nextcloud subdir configuration](https://docs.nextcloud.com/server/16/admin_manual/installation/nginx.html#nextcloud-in-a-subdir-of-nginx)

**Comment by arv4** [comment]
@Maverick1983 my Nextcloud works fine, it's just this one script.

The problem is in `files_external_onedrive/lib/Backend/OneDrive.php`
The javascript file `onedrive.js` does not load correctly if you install Nextcloud in a subfolder.
My solution to fix this issue:
https://gist.github.com/arv4/319079995097d17a4a73f257a3448132

**Comment by Maverick1983** [comment]
With 1.0.5 version I have this error

![image](https://user-images.githubusercontent.com/20558694/65053219-e5b3ba80-d96b-11e9-9847-c4045360bf8a.png)

**Comment by ozboss** [comment]
> With 1.0.5 version I have this error
> 
> ![image](https://user-images.githubusercontent.com/20558694/65053219-e5b3ba80-d96b-11e9-9847-c4045360bf8a.png)

I get the same error.
