### ISSUE TITLE
Logged in, OneDrive not in files section

### ISSUE THREAD

**Issue by KitEJohnson** [hevelius/files_external_onedrive#31]
I've managed to sign into OneDrive by inputting a client_id and client_secret into the external storage option in NextCloud. I then log in to my Office365 account, and NextCloud seems to believe that all is well, giving me a green tick. However, OneDrive never actually shows up in the files section - I seem to have logged in, but can't access my OneDrive at all

**Comment by SchroedersKater** [comment]
I do have exactly the same problem. There are no files visible. Not even under "External Storage".

Please Help!

**Comment by hevelius** [comment]
Could be releteated with #33 and #34 . It's a compatibility issue with most recent version on NC and the app files_external. I'm working to release a new version of files_external_onedrive. I hope to release a new version as soon as possible.

**Comment by hmlendea** [comment]
Any news on this?
