### ISSUE TITLE
Business Account - Possible to do without Admin Approval?

### ISSUE THREAD

**Issue by silentdis** [hevelius/files_external_onedrive#32]
Went through the auth, it appears to work fine, but the final step requires admin approval.

This is a business OneDrive account; there's no way my company would deem it worth the time to even glance at this.

Is there any way to proceed with a user-level OAuth2 of some sort?

**Comment by hevelius** [comment]
For Business accounts Microsoft requires admin approval. I believe there is no way to bypass it. Maybe on Admin side could be granted.
