### ISSUE TITLE
redirect URL is poorly described in documentation

### ISSUE THREAD

**Issue by TheBigBear** [hevelius/files_external_onedrive#41]
I have tried the following URLs and for all of them MS reports that the URL does not correspond with the one registered for the app. MS Azure APP registrations only allow https:// for remote URLs and only for local URLs do they allow http://localhost IF the http:// link does not start with 'localhost' it does no longer allow the URL to be saved.

AFAIK the base URL for my nextcloud installation is 

```
https://cloud.feggm.de/index.php
```
so I tried both with the ```/settings/user/externalstorages``` appended and without it

```
https://cloud.feggm.de/index.php/settings/user/externalstorages
```

and also tried to invent a local literal file system path like 

```
http://localhost/var/www/virtual/fegm/nextcloud-system/index.php/settings/user/externalstorages
```
```
http://localhost/var/www/virtual/fegm/nextcloud-data/index.php/settings/user/externalstorages
```

But none of those worked. How do I find the right Web return URL to be set for the app?

**Comment by timtoo** [comment]
Also, after doing the above, deleting the Redirect URI (because it says it's supposed to be optional) still does not work -- same message: "invalid_request: The provided value for the input parameter 'redirect_uri' is not valid. The expected value is a URI which matches a redirect URI registered for this client application."

**Comment by TheBigBear** [comment]
OK, I fond some help in another filed issue. And I removed /user/ and replaced with with /admin/ and now the redirect URL error message has gone away.

I am now successfully using:

```"https://cloud.feggm.de/index.php/settings/admin/externalstorages"```

So I can close this. But now it always returns a client secret wrong . will open up other issue if it is not already filed.
