### ISSUE TITLE
Compatibility with NC 20

### ISSUE THREAD

**Issue by allusv** [hevelius/files_external_onedrive#43]
NC 20 has a ton of good features and we plan to migrate to it ASAP. We would also like to use onedrive enterprise account for storage. Can you guys please make a version compatible with NC 20?
Thank you

**Comment by hevelius** [comment]
Hi @allusv,

I have started to test files_external_onedrive on NC > 18. I hope to release a new version for NC 20 within the end of the month.

**Comment by hevelius** [comment]
v1.0.9 of files_external_onedrive has been released. Tested on NC 16 to NC 21.
