### ISSUE TITLE
Not able to configure

### ISSUE THREAD

**Issue by richard-dg** [hevelius/files_external_onedrive#47]
Hi, 

I am not able to configure the connection to OneDrive. I followed all the steps:

Installed in app in my nextlcoud, created an app in azure and tried to mount the storage in my Nextcloud. But the configuration fails, when I click on "grant access". The button seems to have no function. Nothing happens, when I click on it. I am not redirected to Microsoft to authenticate. When I click on the tick to save the connection, I get a red exclamation mark and when I reload the page, the connection is not there. 

I run NC 20.0.4 and the newest version of the app. Can you point me to where I can have a look for the problem?

Thanks!

Richard

**Comment by thekarinka** [comment]
Looks like duplicate of #45

**Comment by richard-dg** [comment]
> Looks like duplicate of #45

Thanks, seems to be the same indeed. So I'll close mine. :-)
