### ISSUE TITLE
Size pending

### ISSUE THREAD

**Issue by Maverick1983** [hevelius/files_external_onedrive#5]
I have OneDrive empty storage, and not update "Size column". I have this json on response when check size:

`{"status":"success","data":{"uploadMaxFilesize":2097152,"maxHumanFilesize":"Carica (massimo 2 MB)","freeSpace":-2,"quota":-3,"used":0,"usedSpacePercent":0,"owner":"Luca","ownerDisplayName":"Luca"}}`

**Comment by hevelius** [comment]
Hi @Maverick1983, I have same issue on getting size for folders only. Works for single files.
Maybe a wrong metadata binding. I'll check this as soon as possible.

**Comment by hevelius** [comment]
@Maverick1983 the latest release resolved several issues including size pending. Could you check with your installation?

**Comment by Maverick1983** [comment]
> @Maverick1983 the latest release resolved several issues including size pending. Could you check with your installation?

Now I can't connect OneDrive. See [this](https://github.com/hevelius/files_external_onedrive/issues/3?_pjax=%23js-repo-pjax-container#issuecomment-532258261)
